# Creating and Manipulating Tensors

### Learning Objectives:
* Initialize and assign TensorFlow variables
* Create and manipulate tensors
* Basic TensorFlow math and array operations

In [1]:
import tensorflow as tf
try:
    tf.contrib.eager.enable_eager_execution()
    print("TF imported with eager execution")
except ValueError:
    print("TF already imported with eager execution.")

TF imported with eager execution


## Vector Addition

In [2]:
primes = tf.constant([2, 3, 5, 7, 11, 13], dtype=tf.int32)
print("primes:", primes)

ones = tf.ones([6], dtype=tf.int32)
print("ones:", ones)

just_beyond_primes = tf.add(primes, ones)
print("just beyond primes:", just_beyond_primes)

twos = tf.constant([2, 2, 2, 2, 2, 2], dtype=tf.int32)
primes_doubled = primes * twos
print("primes doubled:", primes_doubled)

primes: tf.Tensor([ 2  3  5  7 11 13], shape=(6,), dtype=int32)
ones: tf.Tensor([1 1 1 1 1 1], shape=(6,), dtype=int32)
just beyond primes: tf.Tensor([ 3  4  6  8 12 14], shape=(6,), dtype=int32)
primes doubled: tf.Tensor([ 4  6 10 14 22 26], shape=(6,), dtype=int32)


Priting a tensor will return its value, shape, dtype. To only see the value return tensor as a numpy array.

In [3]:
print("primes doubled:", primes_doubled.numpy())

primes doubled: [ 4  6 10 14 22 26]


We can also get only shape using get_shape()

In [4]:
print("Shape of primes doubled:", primes_doubled.get_shape())

Shape of primes doubled: (6,)


## Exercise 1: Aritmatic over vectors.

use tf.multiply or tf.pows to just_under_primes_squared. 3*3 -1 = 8

In [5]:
just_under_primes_squared = tf.subtract(tf.multiply(primes, 2), tf.ones([6], dtype=tf.int32))
print(just_under_primes_squared)

tf.Tensor([ 3  5  9 13 21 25], shape=(6,), dtype=int32)


## Reshaping Tensors

 You can use tf.reshape() method to reshape a tensor. You can reshape 8*2 to 2*8 or 4*4. Even you can change dimensions like you can make it 3d 2*2*4 or 1d 16 element tensor.

In [6]:
matrix = tf.constant(
    [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16]], dtype=tf.int32
)

print("Matrix:\n", matrix.numpy())
print("Matrix shape:", matrix.get_shape())

print("*" * 50)

reshaped_8_by_2_matrix = tf.reshape(matrix, [2, 8])
print("Reshaped 8*2 Matrix: \n", reshaped_8_by_2_matrix.numpy())
print("Reshaped 8*2 Matrix shape:", reshaped_8_by_2_matrix.get_shape())

print("*" * 50)
reshaped_4_by_4_matrix = tf.reshape(matrix, [4, 4])
print("Reshaped 4*4 Matrix: \n", reshaped_4_by_4_matrix.numpy())
print("Reshaped 4*4 Matrix shape: ", reshaped_4_by_4_matrix.get_shape())

print("*" * 50)
reshaped_2_by_2_by_4_matrix = tf.reshape(matrix, [2, 2, 4])
print("Reshaped 2*2*4 Matrix: \n", reshaped_2_by_2_by_4_matrix.numpy())
print("Reshaped 2*2*4 Matrix shape:", reshaped_2_by_2_by_4_matrix.get_shape())

print("*" * 50)
reshaped_16_by_1_matrix = tf.reshape(matrix, [16])
print("Reshaped 16*1 Matrix (1-D): \n", reshaped_16_by_1_matrix.numpy())
print("Reshaped 16*1 Matrix (1-D) shape:", reshaped_16_by_1_matrix.get_shape())

Matrix:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
Matrix shape: (8, 2)
**************************************************
Reshaped 8*2 Matrix: 
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
Reshaped 8*2 Matrix shape: (2, 8)
**************************************************
Reshaped 4*4 Matrix: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Reshaped 4*4 Matrix shape:  (4, 4)
**************************************************
Reshaped 2*2*4 Matrix: 
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
Reshaped 2*2*4 Matrix shape: (2, 2, 4)
**************************************************
Reshaped 16*1 Matrix (1-D): 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Reshaped 16*1 Matrix (1-D) shape: (16,)


## Exercise 2: Reshape 2 matrix and multiple them

In [7]:
a = tf.constant([5, 3, 2, 7, 1, 4], dtype=tf.int32)
# shape is (6,)
b = tf.constant([4, 6, 3], dtype=tf.int32)
# shape is (3, )

# for matrix multiplication we can reshape a to (2,3) so that we can do matrix multiplication
a_2_by_3 = tf.reshape(a, [2, 3])
b_3_by_1 = tf.reshape(b, [3, 1])

c = tf.matmul(a_2_by_3, b_3_by_1)
print("Matrix product: \n", c.numpy())
print("Matrix product shape: ", c.get_shape())

Matrix product: 
 [[44]
 [46]]
Matrix product shape:  (2, 1)


## Variables, Initialization and Assignments

In [8]:
# Create a scalar vector and initliaze with 3.
v = tf.contrib.eager.Variable([3])

# Create a vector variable of shape [1, 4], with random values, 
# sampled from a normal distribution with mean 1 and standard deviation 0.35
w = tf.contrib.eager.Variable(tf.random_normal([1, 4], mean=1.0, stddev=0.35))

print("v:", v.numpy())
print("w:", w.numpy())

v: [3]
w: [[0.8443799 0.7835059 1.0376238 1.0404005]]


To change the value of the variable we can use "assign" op.

In [12]:
v = tf.contrib.eager.Variable([3])
print(v.numpy())

# changing value of v
tf.assign(v, [7])
print(v.numpy())

# changing again
tf.assign(v, [5])
print(v.numpy())

[3]
[7]
[5]


When assigning a new value to the variable its shape must be equal to its previous shape

In [14]:
v = tf.contrib.eager.Variable([[1,2,3], [4,5,6]])
print(v.numpy())

try:
    print("Assign [7,8,9] to v")
    v.assign([7,8,9])
except ValueError as e:
    print("Exception: ", e)


[[1 2 3]
 [4 5 6]]
Assign [7,8,9] to v
Exception:  Shapes (2, 3) and (3,) are incompatible
